### ISSUE TITLE
[BUG] missing extension key in composer.json

### ISSUE THREAD

**Issue by pxamike** [pixelant/transliterator#6]
**Describe the bug**
When using composer, it reports:

> The TYPO3 extension package "pixelant/transliterator", does not define an extension key in its composer.json. Please report this to the author of this package. Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)

**Comment by pxamike** [comment]
Guessing this part is needed?

```
  "extra": {
    "typo3/cms": {
      "extension-key": "transliterator"
    }
  }
```

**Comment by MattiasNilsson** [comment]
@pxamike A new release have been made to fix this issue: https://github.com/pixelant/transliterator/releases/tag/v0.1.0
